data:
  base_root: "data"
  dirs:
    queries: "queries"
    blast: "blast"
    filtered_hits: "filtered_hits"
    fasta: 'fasta'
    fasta_modified: 'fasta_modified'

output:
  base_root: "output"
  dirs:
    alignments: "alignments"
    trimmed_alignments: "trimmed_alignments"
    alignments_reports: "alignments_html"
    trimmed_alignments_reports: 'trimmed_alignments_html'
    taxonomy_tables: "taxonomy_tables"
    trees: "trees"

workflow:
  base_root: "workflows"
  dirs:
    rules: "rules"
    scripts: "scripts"

suffix:
  fasta: "fasta"
  alignment: "afa"
  trimmed_alignment: "clipkit.afa"

db:
  base_root: "tax_db"
  name: "refseq_primates"

targets:
  srpx2:
    meta: "sushi repeat-containing protein, SRPX2"
  foxp1:
    meta: "forkhead box protein P1, FOXP1"
  foxp2:
    meta: "forkhead box protein P2, FOXP2"
  slitrk6:
    meta: "SLIT and NTRK-like protein 6, slitrk6"
  dcdc2:
    meta: "doublecortin domain-containing protein 2, dcdc2"
  avpr1a:
    meta: "vasopressin receptor, V1a, avpr1a"
  cntp2:
    meta: "contactin-associated protein-like 2, cntp2"

filters: "LOW QUALITY PROTEIN,fragment,partial"

outgroup:
  group_by_idx: 2           # Use index of column in your table
  group_by_value: "Lemuriformes"
  species_column: 0

blast:
  evalue: 1e-10
  qcov: 50
  max_target_seqs: 500
  outfmt: "6 sseqid length pident qcovs evalue bitscore stitle"

mafft:
  mode: "--localpair"
  max_iter: 1000
  threads: 5

clipkit:
  mode: "kpic-smart-gap"